// TODO: This will be replaced with the correct auth URL once that is setup
export const authUrl = "https://grateful-hamster-0.accounts.dev/";

export const LANGUAGE_PROFICIENCY: Record<string, string> = {
  "BASIC": "Basic",
  "CONVERSATIONAL": "Conversational",
  "FLUENT": "Fluent",
  "NATIVE_BILINGUAL": "Native or Bilingual"
};

export const AVAILABILITY: Record<string, string> = {
  "MORE_THAN_30": "More than 30 hrs/week",
  "LESS_THAN_30": "Less than 30 hrs/week",
  "OPEN_OFFERS": "Open to offers",
  "NONE": "None"
};

export const REJECTED_REASONS_CODE: Record<string, string> = {
  "RATE_TOO_LOW": "Rate Too Low",
  "JOB_REQUIREMENTS_NOT_CLEAR": "Job Requirements Not Clear",
  "PROJECT_TIMELINE_UNREASONABLE": "Project Timeline Unreasonable",
  "NOT_ENOUGH_INFORMATION_PROVIDED": "Not Enough Information Provided",
  "ALREADY_COMMITTED_TO_OTHER_PROJECTS": "Already Committed to Other Projects",
  "NOT_A_GOOD_FIT_FOR_SKILLS": "Not a Good Fit for Skills",
  "CONCERNS_ABOUT_PAYMENT_SECURITY": "Concerns About Payment Security",
  "OTHER": "Other"
};

const categories_raw: Record<string, Record<string, {}>> = {
  "Accounting & Consulting": {
    "Accounting & Bookkeeping": {},
    "Financial Planning": {},
    "Management Consulting & Analysis": {},
    "Other - Accounting & Consulting": {},
    "Personal & Professional Coaching": {},
    "Recruiting & Human Resources": {},
  },
  "Admin Support": {
    "Data Entry & Transcription Services": {},
    "Market Research & Product Reviews": {},
    "Project Management": {},
    "Virtual Assistance": {},
  },
  "Customer Service": {
    "Community Management & Tagging": {},
    "Customer Service & Tech Support": {},
  },
  "Data Science & Analytics": {
    "AI & Machine Learning": {},
    "Data Analysis & Testing": {},
    "Data Design & Visualization": {},
    "Data Extraction/ETL": {},
    "Data Mining & Management": {},
  },
  "Design & Creative": {
    "Art & Illustration": {},
    "Audio & Music Production": {},
    "Branding & Logo Design": {},
    "Graphic, Editorial & Presentation Design": {},
    "NFT, AR/VR & Game Art": {},
    "Performing Arts": {},
    Photography: {},
    "Product Design": {},
    "Video & Animation": {},
  },
  "Engineering & Architecture": {
    "3D Modeling & CAD": {},
    "Building & Landscape Architecture": {},
    "Chemical Engineering": {},
    "Civil & Structural Engineering": {},
    "Contract Manufacturing": {},
    "Electrical & Electronic Engineering": {},
    "Energy & Mechanical Engineering": {},
    "Interior & Trade Show Design": {},
    "Physical Sciences": {},
  },
  "IT & Networking": {
    "Database Management & Administration": {},
    "DevOps & Solution Architecture": {},
    "ERP/CRM Software": {},
    "Information Security & Compliance": {},
    "Network & System Administration": {},
  },
  "Legal": {
    "Contract Law": {},
    "Intellectual Property Law": {},
    "Family Law": {},
    "Corporate Law": {},
    "Real Estate Law": {},
    "Immigration Law": {},
    "Criminal Law": {},
    "Employment and Labor Law": {},
    "Tax Law": {},
    "Personal Injury Law": {},
    "Environmental Law": {},
    "Estate Planning and Probate Law": {},
    "Bankruptcy Law": {},
    "Legal Consulting and Research": {},
    "International Law": {}
  },
  "Sales & Marketing": {
    "Digital Marketing": {},
    "Lead Generation & Telemarketing": {},
    "Marketing, PR & Brand Strategy": {},
  },
  Translation: {
    "Language Tutoring & Interpretation": {},
    "Translation & Localization Services": {},
  },
  "Web, Mobile & Software Dev": {
    "Blockchain, NFT & Cryptocurrency": {},
    "Desktop Application Development": {},
    "Ecommerce Development": {},
    "Game Design & Development": {},
    "Mobile Development": {},
    "Other - Software Development": {},
    "Product Management": {},
    "QA Testing": {},
    "Scripts & Utilities": {},
    "Web & Mobile Design": {},
    "Web Development": {},
  },
  Writing: {
    "Content Writing": {},
    "Editing & Proofreading Services": {},
    "Professional & Business Writing": {},
    "Sales & Marketing Copywriting": {},
  },
};

// const categories = Object.keys(categories_raw).map((group) => ({
//   [group]: Object.keys(categories_raw[group]),
// }));

export const categories_clean: string[][] = Object.keys(categories_raw).reduce(
  (accumulator: any, currVal: any) => {
    return {
      ...accumulator,
      [currVal]: Object.keys(categories_raw[currVal]),
    };
  },
  {}
);


export const countriesData: Record<string, string> = {
  "AF": "Afghanistan",
  "AX": "Aland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua And Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia And Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, Democratic Republic",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote D\"Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island & Mcdonald Islands",
  "VA": "Holy See (Vatican City State)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran, Islamic Republic Of",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle Of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KR": "Korea",
  "KP": "North Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People\"s Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libyan Arab Jamahiriya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MK": "Macedonia",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States Of",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "AN": "Netherlands Antilles",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinian Territory, Occupied",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthelemy",
  "SH": "Saint Helena",
  "KN": "Saint Kitts And Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre And Miquelon",
  "VC": "Saint Vincent And Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome And Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia And Sandwich Isl.",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard And Jan Mayen",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad And Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks And Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "United States Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "VG": "Virgin Islands, British",
  "VI": "Virgin Islands, U.S.",
  "WF": "Wallis And Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

const countriesArr = Object.keys(countriesData).map((key: string) => ({ id: key, name: countriesData[key] }))

export const countries = countriesArr.sort((a, b) => {
  if (a.id === "US") return -1;
  else return 1;
});

export const DAYS_INDEX:any = {
  0: "mondayHours",
  1: "tuesdayHours",
  2: "wednesdayHours",
  3: "thursdayHours",
  4: "fridayHours",
  5: "saturdayHours",
  6: "sundayHours",
}


export const industries: string[] = [
"DevOps", 
"Engineering", 
"Tech",
"Software Development",
"Information Technology (IT)",
"Digital Marketing",
"E-commerce",
"AI & Machine Learning",
"Cybersecurity",
"Cloud Computing",
"Mobile App Development",
"Web Development",
"Data Analytics",
"Gaming",
"Telecommunications",
"Fintech",
"HealthTech",
"EdTech",
"Virtual Reality",
"Blockchain & Cryptocurrency",
"SaaS",
"Other",];

export const JOBDURATION: Record<string, string> = {
  "ONE_TO_THREE_MONTHS": "1 to 3 months",
  "THREE_TO_SIX_MONTHS": "3 to 6 months",
  "MORE_THAN_6_MONTHS": "More than 6 months",
};

// const skills: any[] = [
//   { id: 1, value: "Software Developer" },
//   { id: 2, value: "Finance Accountant" },
//   { id: 3, value: "AI Developer" },
//   { id: 4, value: "QA Tester" },
// ];

export const skills: string[] = [
  "Bookkeeping",
  "Financial Reporting",
  "Tax Preparation",
  "Budgeting",
  "Business Analysis",
  "Strategic Planning",
  "Market Research",
  "Process Improvement",
  "Recruitment",
  "Employee Training",
  "Performance Management",
  "Payroll Processing",
  "Typing",
  "Spreadsheet Management",
  "Data Cleaning",
  "Email Management",
  "Calendar Management",
  "Customer Communication",
  "Task Coordination",
  "Resource Planning",
  "Project Scheduling",
  "Community Management",
  "Tech Support",
  "Machine Learning",
  "Data Analysis",
  "Data Visualization",
  "Data Extraction/ETL",
  "Data Mining",
  "Art & Illustration",
  "Audio Production",
  "Music Production",
  "Branding",
  "Logo Design",
  "Graphic Design",
  "Editorial Design",
  "Presentation Design",
  "NFT Art",
  "AR/VR Design",
  "Game Art",
  "Performing Arts",
  "Photography",
  "Product Design",
  "Video Production",
  "Animation",
  "3D Modeling",
  "CAD Design",
  "Architecture",
  "Chemical Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Electrical Engineering",
  "Electronic Engineering",
  "Mechanical Engineering",
  "Interior Design",
  "Trade Show Design",
  "Physics",
  "Chemistry",
  "Database Management",
  "DevOps",
  "Solution Architecture",
  "ERP/CRM",
  "Information Security",
  "Network Administration",
  "System Administration",
  "Contract Law",
  "Intellectual Property",
  "Family Law",
  "Corporate Law",
  "Real Estate Law",
  "Immigration Law",
  "Criminal Law",
  "Employment Law",
  "Labor Law",
  "Tax Law",
  "Personal Injury Law",
  "Environmental Law",
  "Estate Planning",
  "Probate Law",
  "Bankruptcy Law",
  "Legal Consulting",
  "Legal Research",
  "International Law",
  "Digital Marketing",
  "Lead Generation",
  "Telemarketing",
  "Brand Strategy",
  "Public Relations",
  "Language Tutoring",
  "Interpretation",
  "Translation",
  "Localization",
  "Blockchain Development",
  "Cryptocurrency",
  "Desktop Application Development",
  "Ecommerce Development",
  "Game Design",
  "Game Development",
  "Mobile Development",
  "Product Management",
  "QA Testing",
  "Script Writing",
  "Utility Development",
  "Web Design",
  "Web Development",
  "Mobile Design",
  "Content Writing",
  "Editing",
  "Proofreading",
  "Business Writing",
  "Copywriting",
  "Social Media Management",
  "SEO Optimization",
  "SEM Strategies",
  "Affiliate Marketing",
  "Email Marketing",
  "Video Editing",
  "Motion Graphics",
  "User Interface Design",
  "User Experience Design",
  "Software Debugging",
  "Cloud Computing",
  "API Development",
  "Cybersecurity Analysis",
  "Risk Management",
  "Sustainability Consulting",
  "Renewable Energy Planning",
  "Event Planning",
  "Public Speaking",
  "Training & Development",
  "Logistics Management",
  "Supply Chain Management",
  "Import/Export Compliance",
  "3D Printing",
  "Aerospace Engineering",
  "Biotechnology",
  "Environmental Science",
  "Statistical Analysis",
  "Econometrics",
  "Healthcare Consulting",
  "Nutrition Planning",
  "Fitness Training",
  "Sports Coaching",
  "Psychology",
  "Counseling",
  "Dietetics",
  "Pharmaceutical Consulting",
  "Medical Writing",
  "Clinical Research",
  "Veterinary Services",
  "Agricultural Consulting",
  "Landscaping",
  "Gardening",
  "Urban Planning",
  "Real Estate Appraisal",
  "Property Management",
  "Voice Acting",
  "Scriptwriting",
  "Storytelling",
  "Journalism",
  "Technical Writing",
  "Grant Writing",
  "Academic Research",
  "Historical Research",
  "Translation Editing",
  "Language Instruction",
  "Subtitling",
  "Dubbing",
  "Multimedia Content Creation",
  "Podcasting",
  "Broadcast Journalism",
  "Radio Production",
  "Television Production",
  "Theater Production",
  "Costume Design",
  "Set Design",
  "Lighting Design",
  "Sound Engineering",
  "Event Coordination",
  "Hospitality Management",
  "Tourism Planning",
  "Travel Consulting",
  "Culinary Arts",
  "Baking",
  "Operations Leadership",
  "Web3",
  "Sales Process",
  "Python",
  "Vue.js",
  "Field Marketing",
  "Looker",
  "On-Page SEO",
  "React",
  "Selenium",
  "Pytest",
  "Shopify",
  "Next.js",
  "Off-Page SEO",
  "Sales Operations",
  "JavaScript",
  "WordPress",
  "Integration Testing",
  "Docker",
  "Marketing",
  "GTM Team Design",
  "Node.js",
  "React Native",
  "REST APIs",
  "White box",
  "Webflow",
  "Figma",
  "UX",
  "SQL",
  "Design",
  "Vocal Recording",
  "Black Box",
  "Angular",
  "Salesforce",
  "Web Testing",
  "GTM Startegy",
  "Style Guides",
  "Power BI",
  "CodeIgniter",
  "Writing",
  "Canva",
  "Revenue Operations",
  "Advertising",
  "Regression Testing",
  "CRM Implementation",
  "Local SEO",
  "jQuery",
  "Word",
  "Bootstrap",
  "Bug Reporting",
  "Nuxt UI ",
  "Teachnical SEO",
  "Revenue Model Implementation",
  "Express.js",
  "CSS",
  "IPO/Acquisition Prep",
  "Illustration ",
  "Django",
  "Team Management",
  "HTML",
  "SFX Design",
  "Tableau",
  "APP Testing",
  "Blender",
  "B2B",
  "Product Marketing",
  "GTM KPIs",
  "GTM Tech Stack",
  "PHP",
  "GIT",
  "D3",
  "Zustand",
  "Customer Success Process",
  "sales development",
  "UI",
  "Laravel",
  "Visual Design",
  "Music Composition",
  "Sales Funnel Reporting",
  "Operations Team Design",
  "Document Formatting",
  "Marketing Materials",
  "Game Audio",
  "Business Documentation",
  "2D Art",
  "Buyer Journey",
  "Services Testing",
  "Sales Strategy",
  "Redux",
  "TypeScript",
  "AWS",
  "QA",
  "Tailwind CSS"
];

export const languages: string[] = [
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Bulgarian',
  'Burmese',
  'Catalan',
  'Cebuano',
  'Chichewa',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Corsican',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Esperanto',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Haitian Creole',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Icelandic',
  'Igbo',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Kinyarwanda',
  'Korean',
  'Kurdish (Kurmanji)',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Odia (Oriya)',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Romanian',
  'Russian',
  'Samoan',
  'Scots Gaelic',
  'Serbian',
  'Sesotho',
  'Shona',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu',
];

export const languageProficiency = {
  'BASIC' : 'Basic',
  'CONVERSATIONAL' : 'Conversational',
  'FLUENT' : 'Fluent',
  'NATIVE_BILINGUAL' : 'Native or Bilingual'
};