-- CreateEnum
CREATE TYPE "rejected_reason_code" AS ENUM ('RATE_TOO_LOW', 'JOB_REQUIREMENTS_NOT_CLEAR', 'PROJECT_TIMELINE_UNREASONABLE', 'NOT_ENOUGH_INFORMATION_PROVIDED', 'ALREADY_COMMITTED_TO_OTHER_PROJECTS', 'NOT_A_GOOD_FIT_FOR_SKILLS', 'CONCERNS_ABOUT_PAYMENT_SECURITY', 'OTHER');

-- AlterTable
ALTER TABLE "contract" ADD COLUMN     "rejected_reason_code" "rejected_reason_code";
